# Generated by Django 4.0 on 2021-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('chords', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_playing', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('lyrics', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_playing', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
