# Generated by Django 4.0 on 2022-01-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LyricsChords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='song_length_ms',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_length_ms',
            field=models.IntegerField(default=10000),
        ),
    ]
